// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tektwkcgnqjiuqwrkqdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRla3R3a2NnbnFqaXVxd3JrcWRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NjQyNDQsImV4cCI6MjA3MTI0MDI0NH0.eWqxpA3K8KdRuc7SNBmRubAVPJJbQlEj2ieB7pQmJHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    storageKey: 'sb-insilico-auth-v1',
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
  }
});